// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"server/file/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/file/:imageName",
				Handler: ImageShowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/file/upload/file",
				Handler: fileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/file/upload/image",
				Handler: UploadImageHandler(serverCtx),
			},
		},
	)
}
