// Code generated by goctl. DO NOT EDIT.
// Source: chat_rpc.proto

package server

import (
	"context"

	"server/chat/rpc/internal/logic"
	"server/chat/rpc/internal/svc"
	"server/chat/rpc/proto"
)

type ChatServiceServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedChatServiceServer
}

func NewChatServiceServer(svcCtx *svc.ServiceContext) *ChatServiceServer {
	return &ChatServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServiceServer) UserChat(ctx context.Context, in *proto.UserChatRequest) (*proto.NoneResponse, error) {
	l := logic.NewUserChatLogic(ctx, s.svcCtx)
	return l.UserChat(in)
}
